//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VistaCliente.ProductosServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOProductos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTOProductos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TiendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tienda {
            get {
                return this.TiendaField;
            }
            set {
                if ((object.ReferenceEquals(this.TiendaField, value) != true)) {
                    this.TiendaField = value;
                    this.RaisePropertyChanged("Tienda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductosServiceReference.ProductosServiceSoap")]
    public interface ProductosServiceSoap {
        
        // CODEGEN: Generating message contract since element name ListarProductosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProductos", ReplyAction="*")]
        VistaCliente.ProductosServiceReference.ListarProductosResponse ListarProductos(VistaCliente.ProductosServiceReference.ListarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.ListarProductosResponse> ListarProductosAsync(VistaCliente.ProductosServiceReference.ListarProductosRequest request);
        
        // CODEGEN: Generating message contract since element name producto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarProducto", ReplyAction="*")]
        VistaCliente.ProductosServiceReference.AgregarProductoResponse AgregarProducto(VistaCliente.ProductosServiceReference.AgregarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.AgregarProductoResponse> AgregarProductoAsync(VistaCliente.ProductosServiceReference.AgregarProductoRequest request);
        
        // CODEGEN: Generating message contract since element name producto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        VistaCliente.ProductosServiceReference.ActualizarProductoResponse ActualizarProducto(VistaCliente.ProductosServiceReference.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.ActualizarProductoResponse> ActualizarProductoAsync(VistaCliente.ProductosServiceReference.ActualizarProductoRequest request);
        
        // CODEGEN: Generating message contract since element name producto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        VistaCliente.ProductosServiceReference.EliminarProductoResponse EliminarProducto(VistaCliente.ProductosServiceReference.EliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.EliminarProductoResponse> EliminarProductoAsync(VistaCliente.ProductosServiceReference.EliminarProductoRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarProductoPorNombre", ReplyAction="*")]
        VistaCliente.ProductosServiceReference.BuscarProductoPorNombreResponse BuscarProductoPorNombre(VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarProductoPorNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.BuscarProductoPorNombreResponse> BuscarProductoPorNombreAsync(VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarProductos", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.ListarProductosRequestBody Body;
        
        public ListarProductosRequest() {
        }
        
        public ListarProductosRequest(VistaCliente.ProductosServiceReference.ListarProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarProductosRequestBody {
        
        public ListarProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.ListarProductosResponseBody Body;
        
        public ListarProductosResponse() {
        }
        
        public ListarProductosResponse(VistaCliente.ProductosServiceReference.ListarProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ProductosServiceReference.DTOProductos[] ListarProductosResult;
        
        public ListarProductosResponseBody() {
        }
        
        public ListarProductosResponseBody(VistaCliente.ProductosServiceReference.DTOProductos[] ListarProductosResult) {
            this.ListarProductosResult = ListarProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarProducto", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.AgregarProductoRequestBody Body;
        
        public AgregarProductoRequest() {
        }
        
        public AgregarProductoRequest(VistaCliente.ProductosServiceReference.AgregarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ProductosServiceReference.DTOProductos producto;
        
        public AgregarProductoRequestBody() {
        }
        
        public AgregarProductoRequestBody(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.AgregarProductoResponseBody Body;
        
        public AgregarProductoResponse() {
        }
        
        public AgregarProductoResponse(VistaCliente.ProductosServiceReference.AgregarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarProductoResult;
        
        public AgregarProductoResponseBody() {
        }
        
        public AgregarProductoResponseBody(string AgregarProductoResult) {
            this.AgregarProductoResult = AgregarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProducto", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.ActualizarProductoRequestBody Body;
        
        public ActualizarProductoRequest() {
        }
        
        public ActualizarProductoRequest(VistaCliente.ProductosServiceReference.ActualizarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ProductosServiceReference.DTOProductos producto;
        
        public ActualizarProductoRequestBody() {
        }
        
        public ActualizarProductoRequestBody(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.ActualizarProductoResponseBody Body;
        
        public ActualizarProductoResponse() {
        }
        
        public ActualizarProductoResponse(VistaCliente.ProductosServiceReference.ActualizarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizarProductoResult;
        
        public ActualizarProductoResponseBody() {
        }
        
        public ActualizarProductoResponseBody(string ActualizarProductoResult) {
            this.ActualizarProductoResult = ActualizarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarProducto", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.EliminarProductoRequestBody Body;
        
        public EliminarProductoRequest() {
        }
        
        public EliminarProductoRequest(VistaCliente.ProductosServiceReference.EliminarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ProductosServiceReference.DTOProductos producto;
        
        public EliminarProductoRequestBody() {
        }
        
        public EliminarProductoRequestBody(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.EliminarProductoResponseBody Body;
        
        public EliminarProductoResponse() {
        }
        
        public EliminarProductoResponse(VistaCliente.ProductosServiceReference.EliminarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarProductoResult;
        
        public EliminarProductoResponseBody() {
        }
        
        public EliminarProductoResponseBody(string EliminarProductoResult) {
            this.EliminarProductoResult = EliminarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarProductoPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarProductoPorNombre", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequestBody Body;
        
        public BuscarProductoPorNombreRequest() {
        }
        
        public BuscarProductoPorNombreRequest(VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarProductoPorNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public BuscarProductoPorNombreRequestBody() {
        }
        
        public BuscarProductoPorNombreRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarProductoPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarProductoPorNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public VistaCliente.ProductosServiceReference.BuscarProductoPorNombreResponseBody Body;
        
        public BuscarProductoPorNombreResponse() {
        }
        
        public BuscarProductoPorNombreResponse(VistaCliente.ProductosServiceReference.BuscarProductoPorNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarProductoPorNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VistaCliente.ProductosServiceReference.DTOProductos[] BuscarProductoPorNombreResult;
        
        public BuscarProductoPorNombreResponseBody() {
        }
        
        public BuscarProductoPorNombreResponseBody(VistaCliente.ProductosServiceReference.DTOProductos[] BuscarProductoPorNombreResult) {
            this.BuscarProductoPorNombreResult = BuscarProductoPorNombreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosServiceSoapChannel : VistaCliente.ProductosServiceReference.ProductosServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosServiceSoapClient : System.ServiceModel.ClientBase<VistaCliente.ProductosServiceReference.ProductosServiceSoap>, VistaCliente.ProductosServiceReference.ProductosServiceSoap {
        
        public ProductosServiceSoapClient() {
        }
        
        public ProductosServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ProductosServiceReference.ListarProductosResponse VistaCliente.ProductosServiceReference.ProductosServiceSoap.ListarProductos(VistaCliente.ProductosServiceReference.ListarProductosRequest request) {
            return base.Channel.ListarProductos(request);
        }
        
        public VistaCliente.ProductosServiceReference.DTOProductos[] ListarProductos() {
            VistaCliente.ProductosServiceReference.ListarProductosRequest inValue = new VistaCliente.ProductosServiceReference.ListarProductosRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.ListarProductosRequestBody();
            VistaCliente.ProductosServiceReference.ListarProductosResponse retVal = ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).ListarProductos(inValue);
            return retVal.Body.ListarProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.ListarProductosResponse> VistaCliente.ProductosServiceReference.ProductosServiceSoap.ListarProductosAsync(VistaCliente.ProductosServiceReference.ListarProductosRequest request) {
            return base.Channel.ListarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.ListarProductosResponse> ListarProductosAsync() {
            VistaCliente.ProductosServiceReference.ListarProductosRequest inValue = new VistaCliente.ProductosServiceReference.ListarProductosRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.ListarProductosRequestBody();
            return ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).ListarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ProductosServiceReference.AgregarProductoResponse VistaCliente.ProductosServiceReference.ProductosServiceSoap.AgregarProducto(VistaCliente.ProductosServiceReference.AgregarProductoRequest request) {
            return base.Channel.AgregarProducto(request);
        }
        
        public string AgregarProducto(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            VistaCliente.ProductosServiceReference.AgregarProductoRequest inValue = new VistaCliente.ProductosServiceReference.AgregarProductoRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.AgregarProductoRequestBody();
            inValue.Body.producto = producto;
            VistaCliente.ProductosServiceReference.AgregarProductoResponse retVal = ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).AgregarProducto(inValue);
            return retVal.Body.AgregarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.AgregarProductoResponse> VistaCliente.ProductosServiceReference.ProductosServiceSoap.AgregarProductoAsync(VistaCliente.ProductosServiceReference.AgregarProductoRequest request) {
            return base.Channel.AgregarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.AgregarProductoResponse> AgregarProductoAsync(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            VistaCliente.ProductosServiceReference.AgregarProductoRequest inValue = new VistaCliente.ProductosServiceReference.AgregarProductoRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.AgregarProductoRequestBody();
            inValue.Body.producto = producto;
            return ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).AgregarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ProductosServiceReference.ActualizarProductoResponse VistaCliente.ProductosServiceReference.ProductosServiceSoap.ActualizarProducto(VistaCliente.ProductosServiceReference.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProducto(request);
        }
        
        public string ActualizarProducto(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            VistaCliente.ProductosServiceReference.ActualizarProductoRequest inValue = new VistaCliente.ProductosServiceReference.ActualizarProductoRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            VistaCliente.ProductosServiceReference.ActualizarProductoResponse retVal = ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).ActualizarProducto(inValue);
            return retVal.Body.ActualizarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.ActualizarProductoResponse> VistaCliente.ProductosServiceReference.ProductosServiceSoap.ActualizarProductoAsync(VistaCliente.ProductosServiceReference.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.ActualizarProductoResponse> ActualizarProductoAsync(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            VistaCliente.ProductosServiceReference.ActualizarProductoRequest inValue = new VistaCliente.ProductosServiceReference.ActualizarProductoRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            return ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).ActualizarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ProductosServiceReference.EliminarProductoResponse VistaCliente.ProductosServiceReference.ProductosServiceSoap.EliminarProducto(VistaCliente.ProductosServiceReference.EliminarProductoRequest request) {
            return base.Channel.EliminarProducto(request);
        }
        
        public string EliminarProducto(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            VistaCliente.ProductosServiceReference.EliminarProductoRequest inValue = new VistaCliente.ProductosServiceReference.EliminarProductoRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.EliminarProductoRequestBody();
            inValue.Body.producto = producto;
            VistaCliente.ProductosServiceReference.EliminarProductoResponse retVal = ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).EliminarProducto(inValue);
            return retVal.Body.EliminarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.EliminarProductoResponse> VistaCliente.ProductosServiceReference.ProductosServiceSoap.EliminarProductoAsync(VistaCliente.ProductosServiceReference.EliminarProductoRequest request) {
            return base.Channel.EliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.EliminarProductoResponse> EliminarProductoAsync(VistaCliente.ProductosServiceReference.DTOProductos producto) {
            VistaCliente.ProductosServiceReference.EliminarProductoRequest inValue = new VistaCliente.ProductosServiceReference.EliminarProductoRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.EliminarProductoRequestBody();
            inValue.Body.producto = producto;
            return ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).EliminarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VistaCliente.ProductosServiceReference.BuscarProductoPorNombreResponse VistaCliente.ProductosServiceReference.ProductosServiceSoap.BuscarProductoPorNombre(VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequest request) {
            return base.Channel.BuscarProductoPorNombre(request);
        }
        
        public VistaCliente.ProductosServiceReference.DTOProductos[] BuscarProductoPorNombre(string nombre) {
            VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequest inValue = new VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequestBody();
            inValue.Body.nombre = nombre;
            VistaCliente.ProductosServiceReference.BuscarProductoPorNombreResponse retVal = ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).BuscarProductoPorNombre(inValue);
            return retVal.Body.BuscarProductoPorNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.BuscarProductoPorNombreResponse> VistaCliente.ProductosServiceReference.ProductosServiceSoap.BuscarProductoPorNombreAsync(VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequest request) {
            return base.Channel.BuscarProductoPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<VistaCliente.ProductosServiceReference.BuscarProductoPorNombreResponse> BuscarProductoPorNombreAsync(string nombre) {
            VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequest inValue = new VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequest();
            inValue.Body = new VistaCliente.ProductosServiceReference.BuscarProductoPorNombreRequestBody();
            inValue.Body.nombre = nombre;
            return ((VistaCliente.ProductosServiceReference.ProductosServiceSoap)(this)).BuscarProductoPorNombreAsync(inValue);
        }
    }
}
